### ISSUE TITLE
change repo title

### ISSUE THREAD

**Issue by kubil-ismail** [alkarim99/hire-job-fe-next#1]
change repo name from jire-job-fe to hire-job-web

**Comment by alkarim99** [comment]
![image](https://github.com/alkarim99/hire-job-web/assets/76543950/f225b93f-f043-4fd6-8bb0-b0ca58402ff3)
I have fix this issue, please check, thanks🙏

**Comment by kubil-ismail** [comment]
done
<img width="1680" alt="Screenshot 2023-08-10 at 00 02 10" src="https://github.com/alkarim99/hire-job-web/assets/49361887/c737aa4e-e823-4ab2-92e8-e41ed6ba89f1">
