### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by kubil-ismail** [alkarim99/hire-job-fe-next#2]
Please add search feature in https://hire-job-fe-next.vercel.app/home

**Comment by alkarim99** [comment]
![image](https://github.com/alkarim99/hire-job-web/assets/76543950/d25b6c74-b21f-4399-99cf-3b639281a0a9)
I have fix this issue, please check, thanks🙏

**Comment by kubil-ismail** [comment]
Done
<img width="1680" alt="Screenshot 2023-08-10 at 00 01 13" src="https://github.com/alkarim99/hire-job-web/assets/49361887/2bbbe17e-68d5-48e3-9d90-2f085103722f">
